language: node_js
os: linux
dist: xenial
node_js: [14]

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - yarn

script:
  - yarn test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - yarn run semantic-release
    on:
      branch: master
      condition: $TRAVIS_OS_NAME = linux
